apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "springboot-demo.fullname" . }}
  labels:
    {{- include "springboot-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "springboot-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "springboot-demo.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ include "springboot-demo.name" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "springboot-demo.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}