apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-demo.fullname" . }}
  labels:
    {{- include "springboot-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "springboot-demo.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") (hasKey .Values.service "nodePort") }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
