replicaCount: 2

image:
  repository: v4n1ll4/springboot-demo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080

persistence:
  enabled: true
  size: 1Gi

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: demo.local
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  create: true
  name: springboot-demo-sa

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}