replicaCount: 1

probes:
  enabled: true
  liveness:
    path: /actuator/health
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 2
  readiness:
    path: /actuator/health
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 2


image:
  tag: local

service:
  type: ClusterIP   # CI/로컬 내부 테스트는 ClusterIP면 충분
  port: 80
  targetPort: 8080

persistence:
  enabled: false    # PVC 없이 EmptyDir (템플릿에서 enabled=false면 volume 미마운트)

ingress:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi