replicaCount: 2

image:
  repository: v4n1ll4/springboot-demo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

persistence:
  enabled: false
  size: 1Gi
  storageClass: ""   # 빈 값은 기본 StorageClass 사용

serviceAccount:
  create: true
  name: springboot-demo-sa

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

nodeSelector: {}
tolerations: []
affinity: {}