replicaCount: 3

service:
  type: LoadBalancer

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: demo.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []  # ACM 사용시 여기 secretName 설정

persistence:
  enabled: true
  storageClass: gp2
  size: 5Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70